name: Mesa Ayuda - CI/CD to Render

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest || echo "Skipping tests if none exist"

    # 🚀 Paso agregado: Desplegar automáticamente a Render
    - name: Trigger Render deploy
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        echo "Instalando curl..."
        sudo apt-get update && sudo apt-get install -y curl
        echo "Desplegando a Render..."
        curl -fsS -X POST "$RENDER_DEPLOY_HOOK"
